### PR TITLE
host-utils: non-forking multiplication helper

### PR DESCRIPTION
**Pull request by matrizzo**
Change the 64x64 -> 128 bit multiplication helpers to use 128 bit
integers instead of emulating the behavior in software. This prevents
imul instructions from causing forks on x86.

This requires a patch to the bitfield simplifier to make it handle expressions wider than 64 bits.

Signed-off-by: Matteo Rizzo <matteo.rizzo@epfl.ch>

### CODE REVIEW

**Comment by vitalych** [comment]
So what was the bug in the end? I remember you mentioned some incorrect execution.

**Comment by matrizzo** [comment]
I think the problem was that the arguments weren't being cast to a 128 bit integer and so even though the machine code looked fine when compiling the new helpers in isolation, inlining made it generate incorrect code.
With this version s2e can boot linux without crashing on hanging.

**Comment by matrizzo** [comment]
I ran clang-format on the file I changed but not on the whole repo

**Comment by vitalych** [comment]
There is a problem with jenkins, it can't checkout PRs that are not branches in the repo, I'll fix that.

**Comment by vitalych** [comment]
This is resolved with upgrade to TCG 4.0.

**Pull request closed without merging**
