### PR TITLE
Improvement/arm support1

### PR DESCRIPTION
**Pull request by weizhou-chaojixx**
Add arm cortex-m Cpu emulation.

### CODE REVIEW

**Comment by vitalych** [comment]
Cool! Could you please rebase all your branches?

**Comment by vitalych** [comment]
Also, please follow the instructions here: http://s2e.systems/docs/Contribute.html regarding how the code/commits should look like.

**Comment by weizhou-chaojixx** [comment]
> Cool! Could you please rebase all your branches?
These branches can be directly merged into the original arm support branch. You mean I need to rebase it to master branch?

**Comment by weizhou-chaojixx** [comment]
Sure, I will revise my commit comments.

**Comment by vitalych** [comment]
Yes, please rebase to the master branch. It will much easier for me to review.

**Pull request closed without merging**
