### PR TITLE
op_helper: wrap cc_tmp in helper functions

### LINKED ISSUE #151: cc_tmp accesses in CPUState are not wrapped
cc_tmp is placed in symbolic region, but I found no wrapper is used to access cc_tmp in codebase, cc_src is replaced with CC_SRC etc, why cc_tmp is so special or just a bug?

### PR DESCRIPTION
**Pull request by humeafo**
This fixed https://github.com/S2E/s2e-env/issues/151.

### CODE REVIEW

**Comment by vitalych** [comment]
Cool! Did you check on a small test the behavior of the fix?

**Comment by humeafo** [comment]
I indeed wrote a small program that test this, but on my own modified version , work as expected, however I didn't run it on the vanilla version (applied only this patch) because compilation took a lot of time from scratch( my laptop is very old), so others may check with this to see whether this work as expected:

cxx -DWITH_S2E -I guest/include/s2e/dir test.cc

#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#ifdef WITH_S2E
#include "s2e.h"
#endif

void crash() {
  char* p = 0;
  *p = 0x00;
}

int main(int argc, char* argv[]) {

  uint32_t sval = 1, rval = 0;
#ifdef WITH_S2E
  s2e_make_concolic(&sval, sizeof(sval), "sval");
#endif

  __asm__ volatile (
    "shrl $1, %1\n\t"
    "rcll $1, %1\n\t"
    "movl %1, %0\n\t"
    : "=r" (rval)
    : "r" (sval)
  );

  if (rval) {
    crash();
    printf("rval > 0\n");
  } else {
    printf("rval < 0\n");
  }  
  return 0;
}

**Comment by vitalych** [comment]
Nice, I'll give it a try. Perhaps you could use intrinsic functions instead of inline assembly and put it in the guest-tools repo (create a tests folder there).

**Comment by humeafo** [comment]
@vitalych yes, intrinsic would be better,  I wrote it in asm for rapid testing, I'd think a separate repo for tests would be better instead of place such things in guest-tool folder.

**Comment by vitalych** [comment]
@humeafo yes, separate repo would be better. This would require a lot of additional work. In the meantime, having a simple check say in s2ebios would be good. Btw, s2ebios was intended for testing engine code, without having any OS involved, so it would fit perfectly there.

**Review by vitalych — APPROVED** [review]

**Pull request merged**
